name: Build and Publish Debug APK
run-name: Building Debug APK for Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # triggers only on version tags like v1.0.0

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Rename APK (optional but cleaner for release)
        run: |
          mkdir -p output
          cp app/build/outputs/apk/debug/app-debug.apk output/app-debug-${{ github.ref_name }}.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: output/app-debug-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
